### ISSUE TITLE
nodejs12を捨てて16を追加

### ISSUE THREAD

**Issue by ShuzoN** [ShuzoN/zut#76]
12系捨てて16まで上げるのが目的

12, 14 -> 14, 16にしましょう

**Comment by ShuzoN** [comment]
- [ ] node 12消す
- [ ] 16足す

**Comment by ShuzoN** [comment]
### nodejs 16で実行してみる

```shell
$ nodebrew list
v9.8.0
v10.16.0
v12.13.1
v12.16.1
v16.14.2

current: v16.14.2


[shuzon:ins]  ~/work/zut
$ rm yarn.lock


[shuzon:ins]  ~/work/zut
$ make install test zut/ts ARGS="杉並"
/usr/local/bin/yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning jest > @jest/core > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 14.95s.
/usr/local/bin/yarn test
yarn run v1.22.4
$ jest --config ./jest.config.js
 PASS  test/pressure-level.test.ts
 PASS  test/weather.test.ts
 PASS  test/lambda.test.ts
 PASS  test/zutool.test.ts
 PASS  test/temperature.test.ts
 PASS  test/search.test.ts (5.023 s)

Test Suites: 6 passed, 6 total
Tests:       18 passed, 18 total
Snapshots:   0 total
Time:        6.128 s
Ran all test suites.
✨  Done in 7.67s.
/usr/local/bin/yarn run zut/ts 
yarn run v1.22.4
$ ts-node ./run-zut.ts

/Users/shuzon/work/zut/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:15:32 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.

15     return slack.buildResponse(e);
                                  ~

    at createTSError (/Users/shuzon/work/zut/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/shuzon/work/zut/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/shuzon/work/zut/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/shuzon/work/zut/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/shuzon/work/zut/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/shuzon/work/zut/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [zut/ts] Error 1
```

**Comment by ShuzoN** [comment]
型がより厳格っぽいな

**Comment by ShuzoN** [comment]
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html?icmpid=docs_lambda_rss

そもそもまだlambdaが16に対応してないね。一旦閉じちゃおう
